build_from:
  amd64: "node:22-slim"
  aarch64: "node:22-slim"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: E-Ink Renderer"
  org.opencontainers.image.description: "Renders Home Assistant dashboards as e-ink optimized images"
  org.opencontainers.image.source: "https://github.com/riston/eink-assist-screen"
  org.opencontainers.image.licenses: "MIT"
